const amino_acid = "Amino acid profile of each food is determined by three different analyses. Tryptophan is determined by alkaline hydrolysis, methionine and cystine by performic oxidation and the rest of the amino acids by acid hydrolysis. The amino acid profile of each food is expressed as g/100 g protein.";
const available_carbohydrate = "Available carbohydrate is the sum of total free sugars and total starch. Free sugars are individual monosaccharides (galactose, glucose and fructose) and disaccharides (sucrose, lactose and maltose). The values for available carbohydrate have generally been obtained from the sum of individually analyzed values for these components and will differ with figures for carbohydrate ‘by difference’. Available carbohydrates are those which is digested and absorbed, and are glucogenic in human corresponding to the term ‘glycaemic carbohydrates’.";
const carotenoid = "Vitamin A content is expressed as retinol and provitamin A carotenoid. The groups of plant pigments that are precursors of vitamin A are called carotenoids. Individual carotenoids available in the IFCT includes Lutein, zeaxanthin, lycopene, β-cryptoxanthin, α- carotene, β-carotene, γ-carotene and total carotenoids. The body can utilize these inactive forms once they are converted to the active form, retinol. Vitamin A activity values in Retinol Activity Equivalents (RAE) are calculated from the content of individual carotenoids using appropriate factors. Incidentally, there are many conversion factors for carotenoids and no universal factor exists.";
const chemical_element = "Minerals and trace elements included in the table are Aluminium, Arsenic, Cadmium, Calcium, Chromium, Cobalt, Copper, Iron, Lead, Lithium, Magnesium, Manganese, Mercury, Molybdenum, Nickel, Phospohorus, Potassium, Selenium, Sodium and Zinc. Except phosphorus, levels of all minerals and trace elements are determined by atomic absorption spectroscopy (AAS) or inductively coupled plasma mass spectrophotometry (ICP-MS). Phosphorus was determined by spectrophotometric method.";
const cholesterol = "Cholesterol values are generated primarily by gas liquid chromatographic method in foods of animal origin assuming that cholesterol is present only in animal origin foods. Cholesterol values are expressed as mg/100g food. To convert to mmol cholesterol, divide the values by 386.6.";
const dietary_fibre = "Total dietary fibre (TDF) is made of complex and heterogeneous polymeric materials such as soluble and insoluble polysaccharides and non-digestible oligosaccharides, as well as a range of non-swellable, more or less hydrophobic compounds such as cutins, suberins and lignins. Currently three different AOAC approved methods for measuring TDF values are available. TDF was analyzed using enzymatic gravimetric method (AOAC 991.43).";
const energy = "Food energy is expressed in kilojoules (kJ) calculated based on the Atwater system for determining energy values. The data represent physiologically available energy, which is the energy value remaining after digestive and urinary losses are deducted from gross energy. Food energy in kilojoules (kJ) can be converted using the formula 1 kcal = 4.18 kJ.";
const fatty_acid = "Fatty acid profile is obtained as the percentage of fatty acid methyl esters determined by gas liquid chromatographic (GLC) analysis. Fatty acids are expressed as the actual quantity of fatty acid in mg per 100g of edible potion of food calculated using Sheppard conversion factor as detailed in Weihrauch et al. (1977). Detailed information on individual fatty acids of each food including values for total saturated, monounsaturated and polyunsaturated fatty acids are reported.";
const folate = "Food folate values are analyzed using the trienzyme procedure and liquid chromatography. Food folate was expressed as the sum of one or more individual folate vitamers namely 5-methyl tetrahydrofolate, 10-formyl folic acid, 5-formyl tetrahydrofolic acid and tetrahydrofolic acid.";
const oligosaccharide = "Oligosaccharides are indigestible but the beneficial colonic bacteria break them down in the large intestine. In the recent times there is great interest in the health properties of non-digestible oligosaccharides (NDO) as prebiotic compounds. Data on the oligosaccharide content in foods are very meager, making it difficult to assess oligosaccharide consumption of any population in the world. Therefore, content of raffinose, stachyose, verbascose and ajugoes in key Indian foods is presented.";
const organic_acid = "Organic acids is naturally present in a wide variety of foods especially fruits, berries and vegetables. Organic acids cis-aconitic acid, citric acid, fumaric acid, mallic acid, quinic acid, succinic acid and tartaric acid were determined in single liquid chromatographic run. Soluble, insoluble and total oxalates were determined separately by HPLC method. The organic acids are energy contributing components, although it varies between the different organic acids. According to the Codex Alimentarius Commission’s Guidelines for Nutrition Labeling, the energy conversion factor for organic acids is 13 kJ/g. However, organic acids have not been included in the total energy of foods given in the IFCT.";
const pantothenic_acid = "Pantothenic acid in foods was determined by liquid chromatographic methods.";
const phytate = "Phytate is commonly known as phytic acid, inositol hexaphosphate and IP-6. It has received considerable attention as anti-nutrient because it binds minerals in the digestive tract, making them less available metabolically to our bodies. However, in the recent years, some novel metabolic effects of phytate or some of its degradation products have been recognized as antioxidant and may help fight some cancers and other diseases.";
const plant_sterol = "Plant sterols data on campesterol, stigmasterol, and β-sitosterol are obtained by gas-chromatographic procedures and summed to calculate total phytosterols.";
const polyphenol = "Polyphenols exhibit highly diverse structures characterized by the presence in their structure of one or several phenolic groups. The recognition of the antioxidant properties of polyphenols, and their probable role in the prevention of various diseases associated with oxidative stress has generated great interest. Polyphenols are found abundantly in our diet and over 500 different molecules are known to be present in foods. The IFCT presents data on 37 individual and total polyphenols present in key Indian foods.";
const protein = "Protein values were calculated from the estimated total nitrogen in the food using the Jones (1941) conversion factors. Protein values for soybean and mushrooms contain considerable nonprotein nitrogen (NPN) in several form including urea, purines & pyrimidine. Therefore, NPN was estimated and subtracted from total nitrogen of mushrooms before multiplying with the Jones factor.";
const proximate = "Proximate components include moisture, protein, total fat, ash and carbohydrates. The Difference between 100 and the sum of proximate components including total dietary fibre represents carbohydrate ‘by difference’.";
const saponins = "Saponins consist of a polycyclic aglycones attached to one or more sugar side chains and are found in most vegetables, beans and herbs. Saponins were not destroyed by processing or cooking and have many health benefits.";
const thiamin_riboflavin_niacin = "Thiamin, Riboflavin and Niacin: Thiamin was determined chemically by the thiochrome procedure and riboflavin by microbiological method. Niacin is determined by microbiological method. The values represent only preformed niacin and do not include the niacin contributed by tryptophan, a niacin precursor. Niacin equivalent applies to the sum of the preformed niacin and the amount that could be derived from tryptophan can be calculated as:\n\nNiacin equivalents (mg) = Niacin (mg)+ (Tryptophan, mg / 60).";
const total_fat = "Total fat content of foods is determined by gravimetric methods, including acid hydrolysis and extraction methods using a mixed solvent system of chloroform and methanol. Total fat includes the triglyceride and other lipid components such as glycerol, sterols and phospholipids.";
const vitamin_a = "Vitamin A content is expressed as retinol and provitamin A carotenoid. The groups of plant pigments that are precursors of vitamin A are called carotenoids. Individual carotenoids available in the IFCT includes Lutein, zeaxanthin, lycopene, β-cryptoxanthin, α- carotene, β-carotene, γ-carotene and total carotenoids. The body can utilize these inactive forms once they are converted to the active form, retinol. Vitamin A activity values in Retinol Activity Equivalents (RAE) are calculated from the content of individual carotenoids using appropriate factors. Incidentally, there are many conversion factors for carotenoids and no universal factor exists.";
const vitamin_b6 = "Vitamin B6 occurs in foods as pyridoxine, pyridoxal, pyridoxamine and their phosphates which were estimated by HPLC. The sum of all forms represents vitamin B6.";
const vitamin_c = "Vitamin C data include both ascorbic and L-dehydroascorbic acids, as both forms are biologically active, the sum of which is expressed as total ascorbic acid content.";
const vitamin_d = "Vitamin D have been reported in the IFCT which is lacking in many food composition databases. Ergocalciferol or vitamin D2 content in plant foods measured by LC-MS has been reported for the first time in the world. Cholecalciferol or vitamin D3 in animal source foods including 25 hydroxy-D3 measured by LC-MS/MS has also been reported. The availability of new analytical vitamin D data in foods will permit dietary intake assessment. Vitamin D2 (ergocalciferol) made commercially has been reported to have the similar potency in human. Total vitamin D activity has been taken as the sum of vitamin D3 (cholecalciferol) and five times 25-hydroxy vitamin D3 (25-hydroxy cholecalciferol), where data are available.";
const vitamin_e = "Vitamin E in food is presented as tocopherols and tocotrienols and its isomers. The new Dietary Reference Intake (DRI) for vitamin E (Krinsky, 2000) has stated that with the exception of α-tocopherol all other individual isomers of tocopherols and tocotrienols do not contribute to vitamin E activity, nevertheless, they are included in the database.";
const vitamin_k = "Vitamin K data as phylloquinone in plant foods and menaquinone in animal foods estimated using liquid chromatography are presented in the IFCT.";
const CORPUS = new Map([
  ["water", proximate],
  ["protcnt", protein],
  ["ash", proximate],
  ["fatce", total_fat],
  ["fibtg", dietary_fibre],
  ["fibins", dietary_fibre],
  ["fibsol", dietary_fibre],
  ["choavldf", proximate],
  ["enerc", energy],
  ["thia", thiamin_riboflavin_niacin],
  ["ribf", thiamin_riboflavin_niacin],
  ["nia", thiamin_riboflavin_niacin],
  ["pantac", pantothenic_acid],
  ["vitb6c", vitamin_b6],
  ["folsum", folate],
  ["vitc", vitamin_c],
  ["retol", vitamin_a],
  ["ergcal", vitamin_d],
  ["chocal", vitamin_d],
  ["doh25", vitamin_d],
  ["tocpha", vitamin_e],
  ["tocphb", vitamin_e],
  ["tocphg", vitamin_e],
  ["tocphd", vitamin_e],
  ["toctra", vitamin_e],
  ["toctrb", vitamin_e],
  ["toctrg", vitamin_e],
  ["toctrd", vitamin_e],
  ["vite", vitamin_e],
  ["vitk1", vitamin_k],
  ["vitk2", vitamin_k],
  ["lutn", carotenoid],
  ["zea", carotenoid],
  ["crypxb", carotenoid],
  ["lycpn", carotenoid],
  ["cartg", carotenoid],
  ["carta", carotenoid],
  ["cartb", carotenoid],
  ["cartoid", carotenoid],
  ["al", chemical_element],
  ["as", chemical_element],
  ["cd", chemical_element],
  ["ca", chemical_element],
  ["cr", chemical_element],
  ["co", chemical_element],
  ["cu", chemical_element],
  ["fe", chemical_element],
  ["pb", chemical_element],
  ["li", chemical_element],
  ["mg", chemical_element],
  ["mn", chemical_element],
  ["hg", chemical_element],
  ["mo", chemical_element],
  ["ni", chemical_element],
  ["p", chemical_element],
  ["k", chemical_element],
  ["se", chemical_element],
  ["na", chemical_element],
  ["zn", chemical_element],
  ["cho", available_carbohydrate],
  ["starch", available_carbohydrate],
  ["frus", available_carbohydrate],
  ["glus", available_carbohydrate],
  ["sucs", available_carbohydrate],
  ["mals", available_carbohydrate],
  ["fsugar", available_carbohydrate],
  ["lactose", available_carbohydrate],
  ["f4d0", fatty_acid],
  ["f6d0", fatty_acid],
  ["f8d0", fatty_acid],
  ["f10d0", fatty_acid],
  ["f11d0", fatty_acid],
  ["f12d0", fatty_acid],
  ["f14d0", fatty_acid],
  ["f15d0", fatty_acid],
  ["f16d0", fatty_acid],
  ["f18d0", fatty_acid],
  ["f20d0", fatty_acid],
  ["f22d0", fatty_acid],
  ["f24d0", fatty_acid],
  ["f14d1cn5", fatty_acid],
  ["f16d1cn7", fatty_acid],
  ["f18d1cn9", fatty_acid],
  ["f18d1tn9", fatty_acid],
  ["f20d1cn9", fatty_acid],
  ["f22d1cn9", fatty_acid],
  ["f24d1cn9", fatty_acid],
  ["f18d2cn6", fatty_acid],
  ["f20d2n6", fatty_acid],
  ["f22d2n6", fatty_acid],
  ["f18d3n3", fatty_acid],
  ["f20d3n6", fatty_acid],
  ["f20d4n6", fatty_acid],
  ["f20d5n3", fatty_acid],
  ["f22d5n3", fatty_acid],
  ["f22d6n3", fatty_acid],
  ["fasat", fatty_acid],
  ["fams", fatty_acid],
  ["fapu", fatty_acid],
  ["cholc", cholesterol],
  ["his", amino_acid],
  ["ile", amino_acid],
  ["leu", amino_acid],
  ["lys", amino_acid],
  ["met", amino_acid],
  ["cys", amino_acid],
  ["phe", amino_acid],
  ["thr", amino_acid],
  ["trp", amino_acid],
  ["val", amino_acid],
  ["ala", amino_acid],
  ["arg", amino_acid],
  ["asp", amino_acid],
  ["glu", amino_acid],
  ["gly", amino_acid],
  ["pro", amino_acid],
  ["ser", amino_acid],
  ["tyr", amino_acid],
  ["oxalt", organic_acid],
  ["oxals", organic_acid],
  ["oxali", organic_acid],
  ["caconac", organic_acid],
  ["citac", organic_acid],
  ["fumac", organic_acid],
  ["malac", organic_acid],
  ["quinac", organic_acid],
  ["sucac", organic_acid],
  ["tarac", organic_acid],
  ["dhbenzac34", polyphenol],
  ["hbenzal3", polyphenol],
  ["pcathac", polyphenol],
  ["vanlac", polyphenol],
  ["gallac", polyphenol],
  ["cinmac", polyphenol],
  ["coumaco", polyphenol],
  ["coumacp", polyphenol],
  ["caffac", polyphenol],
  ["chlrac", polyphenol],
  ["ferac", polyphenol],
  ["apigen", polyphenol],
  ["apigen6cgls", polyphenol],
  ["apigen7onshps", polyphenol],
  ["luteol", polyphenol],
  ["kaemf", polyphenol],
  ["querce", polyphenol],
  ["querce3bdgls", polyphenol],
  ["querce3ortns", polyphenol],
  ["querce3bgls", polyphenol],
  ["isormt", polyphenol],
  ["myrct", polyphenol],
  ["rsvrtol", polyphenol],
  ["hespt", polyphenol],
  ["narng", polyphenol],
  ["hespd", polyphenol],
  ["daidzn", polyphenol],
  ["gnstein", polyphenol],
  ["epicatec", polyphenol],
  ["epicategc", polyphenol],
  ["epicatgc3gal", polyphenol],
  ["catec", polyphenol],
  ["galcatecgal", polyphenol],
  ["galcatec", polyphenol],
  ["syrgac", polyphenol],
  ["sinpac", polyphenol],
  ["ellgac", polyphenol],
  ["polyph", polyphenol],
  ["rafs", oligosaccharide],
  ["stas", oligosaccharide],
  ["vers", oligosaccharide],
  ["ajgs", oligosaccharide],
  ["camt", plant_sterol],
  ["stgstr", plant_sterol],
  ["stostrb", plant_sterol],
  ["phytac", phytate],
  ["sapon", saponins],
  ["vitd", vitamin_d],
  ["vitk", vitamin_k],
  ["tocph", vitamin_e],
  ["toctr", vitamin_e],
  ["amiace", amino_acid],
  ["amiacce", amino_acid],
  ["amiacne", amino_acid],
  ["amiac", amino_acid],
  ["orgac", organic_acid],
  ["fauns", fatty_acid],
  ["faess", fatty_acid],
  ["facn3", fatty_acid],
  ["facn6", fatty_acid],
  ["facn9", fatty_acid],
  ["facn5", fatty_acid],
  ["facn7", fatty_acid],
  ["facis", fatty_acid],
  ["fatrn", fatty_acid],
  ["olsac", oligosaccharide],
  ["phystr", plant_sterol],
  ["mnrleq", chemical_element],
  ["mnrlet", chemical_element],
  ["mnrlpet", chemical_element],
  ["mnrlnet", chemical_element],
  ["mnrltx", chemical_element],
  ["carot", carotenoid],
  ["xantp", carotenoid],
  ["cartbeq", carotenoid],
  ["vita", vitamin_a],
]);
module.exports = CORPUS;
